### ISSUE TITLE
feat: exclude routes

### ISSUE THREAD

**Issue by ShahriarKh** [tomcru/holy-loader#17]
It would be awesome if we had the option to exclude specific routes. For example, I do use url query params as the state of my search page: `site.com/search?term=something` and the progress bar is animated many times as the user types. The behavior is correct, because the url is changing (the value of `term` = the value of search input where the user types), and I tried to fix it a bit by debouncing. However, I'd like to exclude this route from holy loader. (Other use cases are page filters and anything that uses "url-based" state management)

In some cases, having the delay option (#2) might be better, but being able to completely exclude some routes or some params will make the library more awesome.

**Comment by tomcru** [comment]
That's a good catch and it makes sense that it shouldn't trigger on URL states like these. I have some ideas in mind I'll try out! ✌️

**Comment by tomcru** [comment]
I've had a look at this behaviour and it is indeed hard to prevent this - because it is correct behaviour (as you noted). The only thing I can think of at the moment is passing an `ignorePaths` prop to HolyLoader with an array of paths to exclude.

It could look something like this (accepting regex):
```typescript
<HolyLoader ignorePaths={[/^\/browse\?query=.*/, /\?query/]} />
```

**Comment by iwasrobbed** [comment]
+1 to an ignore paths option since it gives a lot of flexibility

**Comment by wottpal** [comment]
For us, an `ignoreSearchParams` options would be sufficient (… and quite important too, if we want to stick with HolyLoader. current UX is quite weird).

**Comment by tomcru** [comment]
I've added an `ignoreSearchParams` prop in the latest `2.3.4` release ✌️

https://github.com/tomcru/holy-loader/releases/tag/2.3.4

Tested this as thoroughly as I could, let me know if it's what you expected or if you run into any issues.
