### ISSUE TITLE
Support for RTL layouts

### ISSUE THREAD

**Issue by nahasco** [tomcru/holy-loader#21]
It would be nice if this project supports RTL layouts. 

Basically the progress should run from the right to the left instead of left to right. 

It can be automatic by looking up the `dir` value in `html`, and maybe also a choice to select the direction manually.

Thank you for the great project. Hope this suggestion makes it!

**Comment by r0ld3x** [comment]
let me have a look!

**Comment by tomcru** [comment]
you are very welcome to @r0ld3x! I haven't found the time yet 🙏

**Comment by r0ld3x** [comment]
@tomcru any idea how to do it? 

I tried but itsnot working that way.
I accepted the parameters but I need the https://github.com/tomcru/holy-loader/blob/main/src/HolyProgress.ts#L77 here i used direction and transform but din't worked. :)

**Comment by tomcru** [comment]
Just released this in `2.3.5`! ✌️

https://github.com/tomcru/holy-loader/releases/tag/2.3.5
