### ISSUE TITLE
bug: import error using 2.3.6

### ISSUE THREAD

**Issue by jonathanong** [tomcru/holy-loader#30]
### Description

unable to import as described in the README. seems like the module is exporting `default.default`. I have to do the following to get it to work:

<img width="321" alt="Screenshot 2024-09-20 at 7 15 37 PM" src="https://github.com/user-attachments/assets/7bdf87fc-c330-4665-94f8-390fbae8e03e">

Screenshots:

<img width="345" alt="Screenshot 2024-09-20 at 7 14 44 PM" src="https://github.com/user-attachments/assets/a48d91b4-e3f4-484c-bfd8-47b52aa551d6">
<img width="480" alt="Screenshot 2024-09-20 at 7 14 10 PM" src="https://github.com/user-attachments/assets/6b879c4b-b2cd-4ef4-a167-5efe36e7cd5f">

### Reproduction steps

```bash
unable to do `import HolyLoader from 'holy-loader'`
```

### Logs

```bash
⨯ Internal error: Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```
```


### Browsers

Firefox, Chrome, Safari, Microsoft Edge, Opera

### OS

Mac

**Comment by tomcru** [comment]
Hi @jonathanong 
Thank you for this issue. What bundler are you using?

**Comment by jonathanong** [comment]
I'm using NextJS

**Comment by tomcru** [comment]
@jonathanong can you `npm update holy-loader` and confirm whether this is fixed now?

**Comment by jonathanong** [comment]
yep it's fixed! thank you
