### ISSUE TITLE
Ignore anchors with download attribute set

### ISSUE THREAD

**Issue by mobeigi** [tomcru/holy-loader#31]
With anchor tags you can have HTML like:

```html
<a href="/files/example.txt" download />
```

The `download` attribute tells the browser that the target of the anchor should be downloaded a file.
Docs: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#download

It seems like basically all browsers implement this by download the file async.
Currently, Holy Loader will trigger the trickle for anchors like this on click and it then never terminate the animation.

This is undesirable.
The correct behaviour should be to ignore anchors with the `download` attribute set.

**Comment by tomcru** [comment]
Thanks, will check out ✌️
